package br.com.android.cmi.model;

public  class Funcionalidades {
	
	public static enum Paciente{AVALIAR_MEDICO, AGENDAR_CONSULTA, CONSULTAR_MEDICO, CONSULTAR_CLINICA, CANCELAR_AGENDAMENTO, CONSULTAR_HISTORICO_ATENDIMENTO}

	public static enum Secretaria{AGENDAR_CONSULTA, CONSULTAR_MEDICO, CONSULTAR_CLINICA, CANCELAR_AGENDAMENTO, CONSULTAR_HISTORICO_ATENDIMENTO}
	
	public static enum Medico{CANCELAR_AGENDAMENTO, CONSULTAR_HISTORICO_ATENDIMENTO, REGISTRAR_ATENDIMENTO, DISPONIBILIZAR_AGENDA}

	
	
	public Funcionalidades() {
		// TODO Auto-generated constructor stub
	}

}
